use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        mcp, mstsc, notifications, preferences, quick_pane, recovery, sangfor,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        sangfor::launch_sangfor_client,
        sangfor::inject_sangfor_credentials,
        sangfor::click_sangfor_login,
        mstsc::launch_mstsc,
        mstsc::inject_mstsc_ip,
        mstsc::click_mstsc_connect,
        mcp::start_mcp_server,
        mcp::stop_mcp_server,
        mcp::get_mcp_server_status,
        mcp::regenerate_mcp_token,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
